const enum QRScannerEntityEnum {
  Creditor = "600",
  Enterprise = "910",
  RawMaterial = "100",
  EngineeringBilling = "900",
  EngineeringContractOutsource = "500",
  RealEstateContract = "400",
  RealEstateCustomerAttendance = "301",
  RealEstateCustomerBorrower = "800",
  RealEstateCustomerRequest = "300",
  RealEstateReservation = "401",
  SupplyReceiptNotice = "200",
  SupplyOtherEntries = "205",
  SupplyPriceCollectionSupplier = "650",
  SupplyPurchaseOrder = "700",
  SupplyShoppingRequest = "750",
}
